---
tap_install:
  secrets:
    eso:
      aws:
        region: us-east-2
        tap_install_secrets:
          role_arn: arn:aws:iam::674318584023:role/tap-on-aws--tap-install-secrets
      remote_refs:
        tap_sensitive_values:
          sensitive_tap_values_yaml:
            key: dev/tap-on-aws/tap/sensitive-values.yaml
