---
tap_install:
  values:
    profile: full
    ceip_policy_disclosed: true

    shared:
      ingress_domain: tap-gui.opsdevsys.com
      image_registry:  
        project_path: ""
    #supply_chain: basic
    supply_chain: testing
    #ootb_supply_chain_basic:
    ootb_supply_chain_testing:
      registry:
        server: 674318584023.dkr.ecr.us-east-2.amazonaws.com
        # The prefix of the ECR repository.  Workloads will need
        # two repositories created:
        #
        # tanzu-application-platform/<workloadname>-<namespace>
        # tanzu-application-platform/<workloadname>-<namespace>-bundle
        repository: tanzu-application-platform
      external_delivery: true
      gitops:
        deliverable_repository_owner: "mbahvm"
        deliverable_repository_name: "tap-gitops-v1-deliverable"
        deliverable_branch: main
        deliverable_server_address: "ssh://git@github.com"
        #ssh_secret: ""
        ssh_secret: "git-auth"
        server_address: "ssh://git@github.com"
        repository_owner: "mbahvm"
        repository_name: "tap-gitops-v1-config"
        branch: main
        # repository_prefix: git@github.com/tap-gitops-v1/config-dir
      # scanning:
      #   image:
      #     policy: lax-scan-policy
      #   source:
      #     policy: lax-scan-policy
    buildservice:
      kp_default_repository: 674318584023.dkr.ecr.us-east-2.amazonaws.com/tap-build-service
      # Enable the build service k8s service account to bind to the AWS IAM Role
      kp_default_repository_aws_iam_role_arn: "arn:aws:iam::674318584023:role/tap-build-service"
    contour:
      envoy:
        service:
          type: LoadBalancer
    tap_gui:
      ingressEnabled: true
      ingressDomain: opsdevsys.com
      # tls:
      #   namespace: tap-gui
      #   secretName: tap-gui-cert
      app_config:
        auth:
          allowGuestAccess: true
        supplyChain:
          enablePlugin: true
    # metadata_store:
    #   ingressEnabled: true
    #   ingressDomain: "opsdevsys.com"
    #   app_service_type: ClusterIP
    #   ns_for_export_app_cert: "dev"
    excluded_packages:
    - metadata-store.apps.tanzu.vmware.com
    scanning:
      metadataStore:
        url: "" # Configuration is moved, so set this string to empty.
    # grype:
    #   namespace: dev
    #   targetImagePullSecret: "registries-credentials"
    #   metadataStore:
    #     url: "https://metadata-store.view.tap.opsdevsys.com"
    #     caSecret:
    #       name: store-ca-cert
    #       importFromNamespace: metadata-store-secrets
    #     authSecret:
    #       name: store-auth-token
    #       importFromNamespace: metadata-store-secrets

# #    namespace_provisioner:
#       controller: false
#       additional_sources:
#       - git:
#           url: ssh://git@github.com/mbahvm/tap-gitops-v1
#           ref: origin/main
#           subPath: credentials
#           secretRef:
#             name: ssh
#             namespace: tanzu-sync
#             create_export: true
#         path: _ytt_lib/workload-creds
#       - git:
#           url: ssh://git@github.com/mbahvm/tap-gitops-v1
#           ref: origin/main
#           subPath: additional_resources
#           secretRef:
#             name: ssh
#             namespace: tanzu-sync
#             create_export: true
#         path: _ytt_lib/workload-additional-resources
#       gitops_install:
#         url: ssh://git@github.com/mbahvm/tap-gitops-v1
#         ref: origin/main
#         subPath: ns-provisioner
#         secretRef:
#           name: ssh
#           namespace: tanzu-sync
#           # create_export: true
#       import_data_values_secrets:
#       - name: tenant-secrets
#         namespace: tap-install
#         create_export: true
#       overlay_secrets:
#       - name: workload-git-ssh-overlay
#         namespace: tap-install
#         create_export: true
#     package_overlays:
#     - name: "ootb-supply-chain-testing-scanning"
#       secrets: 
#       - name: "ootb-supply-chain-overlay"
#     - name: "ootb-templates"
#       secrets: 
#       - name: "ootb-template-overlay"  

