---
secrets:
  eso:
    aws:
      region: us-east-2
      tanzu_sync_secrets:
        role_arn: arn:aws:iam::674318584023:role/tap-on-aws--tanzu-sync-secrets
    remote_refs:
      sync_git:
        ssh:
          private_key:
            key: dev/tap-on-aws/tanzu-sync/sync-git/ssh
            property: privatekey
          known_hosts:
            key: dev/tap-on-aws/tanzu-sync/sync-git/ssh
            property: knownhosts
      install_registry_dockerconfig:
        dockerconfigjson:
          key: dev/tap-on-aws/tanzu-sync/install-registry-dockerconfig
